---
apiVersion: v1
#название домена кластера
baseDomain: tryout.local
compute:
- hyperthreading: Enabled
  name: worker
#количество compute нод, для user-provisioned infrastructure должно быть указано 0
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
#количество master нод
  replicas: 3
metadata:
#название кластера
  name: opsh4
networking:
  clusterNetwork:
#блок адресов из которого будут выделяться адреса для подов, не должен пересекаться с существующими сетями
  - cidr: 10.128.0.0/14
#маска выделяемых подам подсетей
    hostPrefix: 24
  networkType: OpenShiftSDN
#пул сервисных ip адресов
  serviceNetwork:
  - 172.30.0.0/16
#конфигурация локального registry, полученная при его создании, требуется для offline установки
imageContentSources:
- mirrors:
  - bastion.opsh4.tryout.local:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.opsh4.tryout.local:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
#сертификат локального registry (/opt/registry/certs/local_registry.crt), требуется для offline установки
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIF5zCCA8+gAwIBAgIJAOjg9DDKQJ1nMA0GCSqGSIb3DQEBCwUAMIGJMQswCQYD
  VQQGEwJSVTEPMA0GA1UEBwwGTW9zY293MRAwDgYDVQQKDAdOZW9mbGV4MQ8wDQYD
  VQQLDAZUUllPVVQxIzAhBgNVBAMMGmJhc3Rpb24ub3BzaDQudHJ5b3V0LmxvY2Fs
  MSEwHwYJKoZIhvcNAQkBFhJhZG1pbkB0cnlvdXQubG9jYWwwHhcNMjAwNjE3MDcy
  OTQ0WhcNMjEwNjE3MDcyOTQ0WjCBiTELMAkGA1UEBhMCUlUxDzANBgNVBAcMBk1v
  c2NvdzEQMA4GA1UECgwHTmVvZmxleDEPMA0GA1UECwwGVFJZT1VUMSMwIQYDVQQD
  DBpiYXN0aW9uLm9wc2g0LnRyeW91dC5sb2NhbDEhMB8GCSqGSIb3DQEJARYSYWRt
  aW5AdHJ5b3V0LmxvY2FsMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
  rdIa3iTYQ9fIyF/1FiIlwQsSjKIL3nxAD1Bz+rAG3bjW3lpKy7QlRXMD1DcP3nr9
  3CbUqSkLcOPnfFEUvTNWVrB3O4+rx7HH0+sNxG3gAfUYXRW3g9iVrnvHnEIr+VKW
  tfiNr5LCs43kj9vc96tywQQ4dZ0khkVzAoN/lHahjGZQtuOO1vhJm1xDLBYHJq/W
  AxF4/T8q8hdZfTvgqxtTFofFvfB17f2+DU6Waqqu7orI1yiUio5rtPJYJ52QehqC
  xOxHW84ZRZ5bGL17PO6j+U0Gp4TUOcsQMCRLKBjA7udGkzAX4rRyEhEeMH9bqB8D
  gNs7zHZlyVf0RzJDM9FfxYNp5K6Wjdex5jy7UaCIcXwakfyOHRKx/Y4XNHhU+j5I
  7lNGd+OkE6t8n/S4gtSOdTUa1xEAi6iuT3jsK7B6rCSFAnTs6Q2CkI11xRDBegp9
  qvChMkL6FRLgghetvyiurwH8P3kyc7hrH9s0k0lFniLtZjNqPnFPXlLfdp5TBVEJ
  QfUxVBdFSynC/z5ixqf9woeoGDjnDPKS1FINkS7T/WzsjIfY1XM0V1d1j/kQlC8d
  KGKssF+YO3JzWN0BsVVDzTb2opeBSOmrbsknu0wDJpSQ+2uRzAesR6mwys27GvjV
  REcysnC4dlY/1IJVKsHygUg2bYqC8FKxX2qRxnl2FPkCAwEAAaNQME4wHQYDVR0O
  BBYEFE9MPrBOmXjETfSPF8jcaaV/vN7FMB8GA1UdIwQYMBaAFE9MPrBOmXjETfSP
  F8jcaaV/vN7FMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGaum1gg
  kd92XXfN0DPx5i5RTXKB90gCAGDK3IEi8ZeVAqUOdZZy2qfLgFGG4NGXUxR+kyJL
  tVkABzm8Cv/xmICyztFyZW75A4Z4GLlMuTYPJriUmtveDy2Q4HQ95jALDMu/DLwY
  MAfmxM3fBSkbFTMYVH4c861eo0m99LijR//tD3Qik0mwNK4uHqmhqQJ0hbwc016A
  7yzoWYm7ORf2/8MAzd/qEyL61qP0Upnfk7Rvt8f3eUDIMtLd6rpWU3BDqFWeHez/
  ugqs4NRep7ghd2HR3Q6iCtD+23yQePOORpkXa9/rtPEuwd7TyzN6D6WptjcUJ307
  Z6mYlR57wnY2OhgVAjQoC8mhsTakVv4846onYGEPHEXtrwgb0oBJG2lRN3K2A1EE
  vX0hUDo3GJl0Taq3EAf3aHIdH2lfM0gFgAQxHt6x3Z9MPJJRJL+SgF2aeuHrhV3I
  cWZ2pYY96Z3EMBNjcEVPTmahnyaBBKY4XgjcKTGNFTob8+X/bB8nwsgPhNoAavrJ
  koKV82nQGdQi1Qki+TK8l0GP9o74Mj+fENxgtOkFERdCC0GMG/jAUhp8NZxKGMBh
  bMBHskgTQ2GGJq/PmA5knwUcCOK/CcR6m5763AxHidhNaYwZDo/27WpExo9aygDK
  cJkBU0jCzh/gP+EoqSV1dwB80d86V2IM4nIp
  -----END CERTIFICATE-----
#для bare metal должно быть none
platform:
  none: {}
fips: false
#pull-secret для доступа к репозиториям
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2x1bWluYXZyMWRyZjlsa2xxYTRvbjhvN2s0am1mamE4ZXY3Ojk3VlpJU1BKTDdZOENWQ1JSUkpTT09EQU9TRVAxWFozQ0lPRUg2RTk0WFZBTUdEQjBBQko0SE40UENGQkk5S0g=","email":"megaperch@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2x1bWluYXZyMWRyZjlsa2xxYTRvbjhvN2s0am1mamE4ZXY3Ojk3VlpJU1BKTDdZOENWQ1JSUkpTT09EQU9TRVAxWFozQ0lPRUg2RTk0WFZBTUdEQjBBQko0SE40UENGQkk5S0g=","email":"megaperch@gmail.com"},"registry.connect.redhat.com":{"auth":"NTM1MTk5NzN8dWhjLTFkUkY5bGtsUUE0b244TzdLNEptZmpBOGV2NzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlPR1V6T1RJMFl6RTFabUkwTXpKallUZzFaV1F6TnpZNU16QXhZelprWVNKOS5pdEtndHpRRk1JcTNHYVRZX0VlNG5ZUF9VWDRQWUlSa1d6VkwxdTFuWl96Q2dLOUlPODZYbUZOOVBQRElocGhCSlFoTXNHYk11c0VlbWpZMDc3WkpycXJFbEg5TEdxODJVSUFseEt6aUd2czNaR3AxMmRhcmlSc1NJT0hxbWtRZE40M0VaSDdWS1ZkeGdwT0gtNUM4SXRhdnJtUzlfeW1OSlc1ODk2cDEzU29YQU9QTUFVT1MwdGd3dVhhcS1BRFhHdHBiZFZCcmVPaWxlSnBSNzUxV2UtUE9qNVQzbS1lekZfaW1PbTJ0dDVDUE9nM3R3eV9Jd2FoQWpFUTRUV0lRdlo5emV4TDVId1JlUU94SXlpOFpETGtHenI5QzJyQ0tHNVNUYU9WYTF2TllPTllvZHI1Z2FPRkJJWEtLajhWOFFsOGU5eVE3ajgydF9mczVtcVJ5RWJ3bkNhZHVoWjI5VTZsN3F1ekVCS1haZE1Va3gzdzZhZ2lRNXZWRzRibHVFRzZpUXJ4algzZUk4aUhrVDZNaFozY2psR1o5cy1TeGhFMVRBLTh1ZmF1ZGFQci1kcXp4S1ltbUktd2Ita1F4WXhWYW1YaWhQdTB5cG9oMFhWcUJyejdBTFFxSWsyelhRQjI0M0ZDdTh1ZU44SFRQTG9nblNfMGJ3SlBObnV2T0FmcFhBSWpMYmdzdWsxZ2Q1WGVUcmNKY2FMUGNveGNCSFU4T2lQckptOGN3eDR5WGl4QVJibHhTZ2hNWnVZVnFNZHJjWDRXdi1NS0JfbzVmUTlPVXBUd1BGaEtVOUM5WnM5WDB5ejhfUEk0bVJYby1MNTVtS05JS0JQNkRvQk9nWFdHaTJDOHFDR2UtMEhkYVBqa0o0X2ptODV6bjRQa05sN1hCNndreF9TWQ==","email":"megaperch@gmail.com"},"registry.redhat.io":{"auth":"NTM1MTk5NzN8dWhjLTFkUkY5bGtsUUE0b244TzdLNEptZmpBOGV2NzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlPR1V6T1RJMFl6RTFabUkwTXpKallUZzFaV1F6TnpZNU16QXhZelprWVNKOS5pdEtndHpRRk1JcTNHYVRZX0VlNG5ZUF9VWDRQWUlSa1d6VkwxdTFuWl96Q2dLOUlPODZYbUZOOVBQRElocGhCSlFoTXNHYk11c0VlbWpZMDc3WkpycXJFbEg5TEdxODJVSUFseEt6aUd2czNaR3AxMmRhcmlSc1NJT0hxbWtRZE40M0VaSDdWS1ZkeGdwT0gtNUM4SXRhdnJtUzlfeW1OSlc1ODk2cDEzU29YQU9QTUFVT1MwdGd3dVhhcS1BRFhHdHBiZFZCcmVPaWxlSnBSNzUxV2UtUE9qNVQzbS1lekZfaW1PbTJ0dDVDUE9nM3R3eV9Jd2FoQWpFUTRUV0lRdlo5emV4TDVId1JlUU94SXlpOFpETGtHenI5QzJyQ0tHNVNUYU9WYTF2TllPTllvZHI1Z2FPRkJJWEtLajhWOFFsOGU5eVE3ajgydF9mczVtcVJ5RWJ3bkNhZHVoWjI5VTZsN3F1ekVCS1haZE1Va3gzdzZhZ2lRNXZWRzRibHVFRzZpUXJ4algzZUk4aUhrVDZNaFozY2psR1o5cy1TeGhFMVRBLTh1ZmF1ZGFQci1kcXp4S1ltbUktd2Ita1F4WXhWYW1YaWhQdTB5cG9oMFhWcUJyejdBTFFxSWsyelhRQjI0M0ZDdTh1ZU44SFRQTG9nblNfMGJ3SlBObnV2T0FmcFhBSWpMYmdzdWsxZ2Q1WGVUcmNKY2FMUGNveGNCSFU4T2lQckptOGN3eDR5WGl4QVJibHhTZ2hNWnVZVnFNZHJjWDRXdi1NS0JfbzVmUTlPVXBUd1BGaEtVOUM5WnM5WDB5ejhfUEk0bVJYby1MNTVtS05JS0JQNkRvQk9nWFdHaTJDOHFDR2UtMEhkYVBqa0o0X2ptODV6bjRQa05sN1hCNndreF9TWQ==","email":"megaperch@gmail.com"}}}'
#публичный ssh ключ для доступа к хостам кластера по ssh под пользователем core
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTkzYkuDvXg9+7/VzWrMUn9KxRRu4PeWwZCVlydyA8fm47fl125MF18ISQqu4OxsA2uotPL8ldgUCEJ16geIP6S0u0nxky3qs1QDn6hqodk9pXBEHlbBeFoHnLjvUEZEv/MxTDoSjdxprCflR3eIPNfE7mBAP8p/IKCTNtWxemssRM9R7Z7bU1+/A5UWQejsJkOibAtBGUET/if3R9Sdug/b8VrMEpCU/mScd6byWsawlBB5h0ds8jwvT42ukrHJnrsVNbOzuNXBnDR0RMcbt1Gawg77e91+t8gq0b30dTx5RAr5fdw+YNDnz8cqkBaFqTVg9iac0hrQDTECA1tRMV root@bast-test'
