global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.19.19.93:9090']
  - job_name: 'node_exporter_centos_bastion'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.19.19.93:9100']

