apiVersion: "v1"
kind: "Pod"
metadata:
  name: "recyler-pod-"
  namespace: "openshift-infra"
spec:
  activeDeadlineSeconds: 60
  restartPolicy: "Never"
  serviceAccountName: "pv-recycler-controller"
  containers:
    -
      name: "recyler-container"
      image: "docker.io/openshift/origin-recycler:v3.11.0"
      command:
      - "/usr/bin/openshift-recycle"
      args:
      - "/scrub"
      volumeMounts:
        -
          mountPath: "/scrub"
          name: "vol"
      securityContext:
        runAsUser: 0
  volumes:
    -
      name: "vol"
