apiVersion: v1 
kind: PersistentVolume 
metadata:  
  name: pv-nfsvol5 
spec:  
  capacity:    
    storage: 3Gi  
  accessModes:    
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  nfs:    
    path: /exports/nfsvol5    
    server: 172.19.19.93
    readOnly: false 
