apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: gitlab
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: gitlab-crb
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
    - kind: ServiceAccount
      name: gitlab
      namespace: test
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: gitlab-ce
      app.kubernetes.io/component: gitlab-ce
      app.kubernetes.io/instance: gitlab-ce
    name: gitlab-ce
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: gitlab/gitlab-ce
      from:
        kind: DockerImage
        name: gitlab/gitlab-ce
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: gitlab-ce
      app.kubernetes.io/component: gitlab-ce
      app.kubernetes.io/instance: gitlab-ce
    name: gitlab-ce
  spec:
    replicas: 1
    selector:
      deploymentconfig: gitlab-ce
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: gitlab-ce
      spec:
        containers:
        - image: gitlab/gitlab-ce
          name: gitlab-ce
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
          - mountPath: /etc/gitlab/gitlab.rb
            name: gitlab-rc
        volumes:
        - name: gitlab-rc
          configMap:
            name: gitlab-rc
        securityContext: {}
        serviceAccountName: gitlab
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - gitlab-ce
        from:
          kind: ImageStreamTag
          name: gitlab-ce:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: gitlab-ce
      app.kubernetes.io/component: gitlab-ce
      app.kubernetes.io/instance: gitlab-ce
    name: gitlab-ce
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      deploymentconfig: gitlab-ce
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: gitlab-ce
    name: gitlab-ce
  spec:
    port:
      targetPort: 80-tcp
    to:
      kind: Service
      name: gitlab-ce
      weight: 100
    wildcardPolicy: None

