apiVersion: v1 
kind: PersistentVolume 
metadata:  
  name: pv-nfsvol8
spec:  
  capacity:    
    storage: 3Gi  
  accessModes:    
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  nfs:    
    path: /exports/nfsvol8    
    server: 172.19.19.93
    readOnly: false
  claimRef:
    name: gitlab-test-data
    namespace: test
