apiVersion: v1 
kind: PersistentVolume 
metadata:  
  name: pv-nfsvol10 
spec:  
  capacity:    
    storage: 3Gi  
  accessModes:    
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  nfs:    
    path: /exports/nfsvol10   
    server: 172.19.19.93
    readOnly: false
  claimRef:
    name: gitlab-test-conf
    namespace: test
