apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: gocalc-test
  labels:
    app: gocalc
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: gocalc
  template: 
    metadata: 
      labels: 
        app: gocalc
    spec: 
      containers:
        - name: gocalc
          image: vozerov/gocalc
          port:
          - containerPort: 7000
            protocol: TCP
